openapi: 3.1.0
info:
  title: Excel to Coda API
  version: "1.0"
servers:
  - url: https://excel-coda-server.onrender.com
paths:
  /transcribe:
    post:
      operationId: transcribeExcelToCoda
      summary: Transcribe Excel to Coda
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                coda_token:
                  type: string
                doc_id:
                  type: string
                table_name:
                  type: string
                web_search_columns:
                  type: string
      responses:
        '200':
          description: Success
